name: Build & Staging Deploy
on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 20

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'
        
      - name: Remove Package Lock and Update Dependencies
        run: rm -f package-lock.json
        
      - name: Install Dependencies
        run: npm install

      - name: Generate Distribution
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_GANTT_KEY: ${{ secrets.VITE_GANTT_KEY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: ./dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: distribution
          path: ./dist
      - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        name: Azure Blob Upload with Destination folder defined
        with:
          connection_string: ${{secrets.CONNECTION_STRING}}
          container_name: $web
          source_folder: ./dist
          clean_destination_folder: true
      - name: Purge Cache
        uses: nathanvaughn/actions-cloudflare-purge
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
          cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
          hosts: |
            admin.ncldata.dev