name: Build & Staging Deploy
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'

      - name: Install Dependencies
        run: yarn

      - name: Generate Distribution
        run: yarn build
        env:
          VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
          VUE_APP_GANTT_KEY: ${{ secrets.VUE_APP_GANTT_KEY }}

      - name: Deploy
        uses: lauchacarro/Azure-Storage-Action@v1.1
        with:
          enabled-static-website: 'true'
          folder: 'dist'
          index-document: 'index.html'
          error-document: 'index.html'
          connection-string: ${{ secrets.CONNECTION_STRING }}